<!DOCTYPE html>
<html>
    <body>
<p style="text-align: center; font-size: 25px;"><strong ></strong ><a href="https://www.facebook.com/hashtag/%E1%9E%9F%E1%9E%BB%E1%9E%81%E1%9F%97%E1%9E%80%E1%9F%8F%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9F%8B%E1%9E%91%E1%9F%85?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>សុខៗក៏បាត់ទៅ</strong></a><a href="https://www.facebook.com/hashtag/%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9E%98%E1%9E%A0%E1%9E%B6%E1%9E%9F%E1%9E%98%E1%9E%BB%E1%9E%91%E1%9F%92%E1%9E%9A?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>បាត់មហាសមុទ្រ</strong></a></p>
<p style="text-align: center;"><strong>និពន្ធដោយ</strong><strong>: </strong><a href="https://www.facebook.com/hashtag/%E1%9E%98%E1%9E%99%E1%9E%BC%E1%9E%9A%E1%9F%89%E1%9E%B6_%E1%9E%9B%E1%9E%B6%E1%9E%80%E1%9F%8B%E1%9E%98%E1%9E%BB%E1%9E%81?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">មយូរ៉ាលាក់មុខ</a>&nbsp;<a href="https://www.facebook.com/hashtag/%E1%9E%A0%E1%9F%81%E1%9E%84_%E1%9E%82%E1%9E%B8%E1%9E%98%E1%9E%A1%E1%9E%B6%E1%9E%84?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">ហេង គីមឡាង</a>&nbsp;</p>

<p><strong></strong>&nbsp;&nbsp;'' ច្រូក ច្រូក ច្រូក '' សម្លេងជើងនារីវ័យក្មេងម្នាក់ ដើរលុយទឹកលឿនៗ ហាក់មានសភាពភ័យខ្លាចតក់ស្លុតយ៉ាងខ្លាំង ព្រមទាំងមានរបួសឈាមស្មារខាងឆ្វេង។ មើលទៅនាងដូចជាកំពុងរត់គេចពីអ្វីម៉្យាង នៅតាមដងឆ្នេរសមុទ្រនាពេលយប់អធ្រាត។ ឆ្លងផុតពីផ្ទៃទឹកសមុទ្រភ្លាម នារីវ័យក្មេងក៏ផ្តួលខ្លួនដេកនៅលើវាលខ្សាច់ឆ្នេរសមុទ្រ ព្រោះតែអស់កម្លាំងពន់ពេក ទើបបណ្តាលអោយទន់ជង្គង់ដួលចុះ ស្ទើរតែដកដង្ហើមមិនទាន់បានស្រួលបួលផង សម្លេងលាន់ផ្ទុះ '' ផូង! '' ពីកណ្តាលផ្ទៃសមុទ្រ បង្ករអោយមានក្តីរន្ធត់ជាខ្លាំង ធ្វើអោយនារីវ័យក្មេងនោះ ទោះបីជាកំពុងស្ថិតក្នុងសភាពទ្រុឌទ្រោម របួសពេញខ្លួន សឹងកម្រើកលែងរួច ក៏នាងត្រូវតែព្យាយាមជម្នះក្រោកឈរឡើងរត់ចេញអោយឆ្ងាយពីកន្លែងនោះជាប្រញាប់។</p>
<p>រលកដ៏ធំវាយបោកមកលើផ្ទៃខ្សាច់ឆ្នេរសមុទ្រ អូឈើទាល ផ្គរលាន់គគ្រឹកគគ្រាក់ហាក់ចង់បង្អួតអំណាចរបស់កងពលសេនានៃស្តេចទេវរាជ ក្រោកឡើងពីបាតមហាសមុទ្រដឹកនាំ កងពលសេនាពូជពង្សាវតា គ្រប់គ្រងលើភពឋាន នគរឯបាតសមុទ្រដ៏សែនជ្រៅ។ សេនាសមុទ្រ បំពាក់សម្លៀកបំពាក់ឯកសណ្ឋាន ជារចនាបទ មច្ចាមហានគរ ដៃមានកាន់លំពែងធ្វើអំពី ជំពុះត្រីដាវ បានបើកផ្លូវអោយ អធិរាជ ទេវរាជ ស្តេចមហាសមុទ្រ យាងចុះពីលើខ្នងសត្វសេះសមុទ្រយក្សមក ជើងជាន់លើផ្ទៃខ្សាច់សមុទ្រ សម្លឹងមើលស្តាំ មើលឆ្វេង ក្នុងបំណងស្វែងរកអ្វីម៉្យាង។</p>
<p>ឆ្នាំ ២០១៤, ក្រុងព្រះសីហនុ ខេត្ត កំពង់សោមវេលាម៉ោង ១:៣០ ថ្ងៃរសៀល...</p>
<p>មេឃភ្លៀង '' ឈូ!!! '' ក្មេងប្រុសស្លូតមួយរូបសម្លៀកពាក់ឯកសណ្ឋានសិស្សវិទ្យាល័យ បានរត់ចូលក្នុងសាលាយ៉ាងលឿន។</p>
<p>សម្លេងសិស្សនៃថ្នាក់ទី ១០B បាននាំគ្នាសើចលាន់ពេញថ្នាក់មួយទំហឹង ពេលបានឃើញសភាពរបស់ ក្មេងប្រុសម្នាក់នោះ ទទឹកភ្លៀងជោក។ ក៏ព្រោះតែរូបគេជាក្មេងដែលក្រីក្រជាងគេក្នុងថ្នាក់ ដែលមានតែកង់កញ្ចាស់ធាក់មករៀន មិនមានឡានទំនើបជូនមក មិនមានអ្នកបាំងឆ័ត្រអមចូលសាលាដូចគេ។ ភក្តី បានត្រឹមឱនមុខចុះ ដើរកាត់ហ្វូងមនុស្សដែលសើចចំអកអោយរូបគេជារាងរាល់ថ្ងៃ សំដៅទៅអង្គុយតុខាងក្រោយគេ ដែលជាកន្លែងអង្គុយរបស់នាយ។</p>
<p>បូរ៉ា រាងធាត់ដូចជ្រូក សក់រួញៗសម្បុរស ពាក់វែនតាពណ៍មាស ទំនងជាកូនអ្នកមានខ្លាំង មានចរឹករើសអើង បានប្រតិកម្មស្រែកបែកសម្លេងភ្លាមៗគ្រាន់តែភក្តីបានមកអង្គុយចុះក្បែររូបគេ បូរ៉ា ក៏ស្ទុះទាញកាបូបរៀនដោយអាកប្បកិរិយាខ្ពើមរអាដើរចេញទៅអង្គុយកន្លែងផ្សេងភ្លាមៗ ទុកអោយ ភក្តី នៅអង្គុយតែម្នាក់ឯង បណ្តាលអោយមិត្តរួមថ្នាក់ដទៃទៀត កាន់តែបានចិត្តបង្កើនសម្លេងសើចចំអកអោយ ភក្តី លើសដើម។ ក៏ប៉ុន្តែ ភក្តី នៅតែរក្សាអត្តចរឹកសុភាព ស្លូតបូតរបស់រូបគេ អង្គុយស្ងៀមក្រឡេកកែវភ្នែកសម្លឹងមើលទៅផ្ទៃមេឃចុះអព្វ ពេលមេឃភ្លៀង ដើម្បីបន្ធូរអារម្មណ៍។</p>
<p><strong>&nbsp;</strong></p>
    </body>
</html>