<!DOCTYPE html>
<html>
    <body>
<p style="text-align: center; font-size: 25px;"><strong ></strong ><a href="https://www.facebook.com/hashtag/%E1%9E%9F%E1%9E%BB%E1%9E%81%E1%9F%97%E1%9E%80%E1%9F%8F%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9F%8B%E1%9E%91%E1%9F%85?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>សុខៗក៏បាត់ទៅ</strong></a><a href="https://www.facebook.com/hashtag/%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9E%98%E1%9E%A0%E1%9E%B6%E1%9E%9F%E1%9E%98%E1%9E%BB%E1%9E%91%E1%9F%92%E1%9E%9A?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>បាត់មហាសមុទ្រ</strong></a></p>
<p style="text-align: center;"><strong>និពន្ធដោយ</strong><strong>: </strong><a href="https://www.facebook.com/hashtag/%E1%9E%98%E1%9E%99%E1%9E%BC%E1%9E%9A%E1%9F%89%E1%9E%B6_%E1%9E%9B%E1%9E%B6%E1%9E%80%E1%9F%8B%E1%9E%98%E1%9E%BB%E1%9E%81?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">មយូរ៉ាលាក់មុខ</a>&nbsp;<a href="https://www.facebook.com/hashtag/%E1%9E%A0%E1%9F%81%E1%9E%84_%E1%9E%82%E1%9E%B8%E1%9E%98%E1%9E%A1%E1%9E%B6%E1%9E%84?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">ហេង គីមឡាង</a>&nbsp;</p>

<p>&nbsp;&nbsp;សម្លេង វាយជួង ចូលរៀន... មេឃក៏ចាប់ផ្តើមរាំងភ្លៀង អ្នកគ្រូភាសាខ្មែរ ដើរចូលមកក្នុងថ្នាក់ សិស្សទាំងអស់នៃថ្នាក់ទី ១០B ក្រោកឈរឡើងដើម្បីជំរាបសួរអ្នកគ្រូ។ អ្នកគ្រូ ងាកទៅមាត់ទ្វាររួចវាចារហៅ៖<br /> '' រីណា! ចូលមកក្នុងថ្នាក់មកកូន ''<br /> '' ចាសអ្នកគ្រូ '' សម្លេងដ៏គ្រលួច លួចឆក់ប្រលោម ដួងចិត្តមិត្តរួមថ្នាក់បុរសៗទាំងអស់ បានរសាត់ចូលមកក្នុងថ្នាក់រៀន មុនវត្តមាននៃម្ចាស់សំនៀងបានឈានជើងដើរចូលមក បង្ហាញនូវរូបរាងក្មេងស្រីរូបរាងស្រស់សោភា ដងខ្លួនល្វត់ល្វន់សមនឹងសម្លៀកបំពាក់ឯកសណ្ឋានសិស្សល្អឥតខ្ចោះ សក់ខ្លីត្រឹមស្មារបន្តិច ទង្គិចនឹងខ្យល់ធម្មជាតិដែលវាយចូលមកតាមមាត់បង្អួច គួចបង្វែរអោយសក់របស់នាងរលាស់ផុតវែកកំបាំងមុខ អោយគ្រប់គ្នាបានឃើញសម្រស់នៃវង់ភក្ត្រារបស់នាងយ៉ាងច្បាស់ពេញលេញ ដូចកំពុងគយគន់ដួងព្រះចន្ទថ្ងៃពេញបូរមី កណ្តាលសួនស្នេហ៍ដង្ហែវាយោត្រជាក់ទាក់យកបេះដូង បុរស់ៗគ្រប់គ្នាសឹងតែដាច់ខ្យល់ផុតវិញ្ញាណទៅ មួយរំពេច។</p>
<p>'' នេះគឺ ច័ន្ទ រីណា មិត្តរួមថ្នាក់ថ្មីរបស់ប្អូនៗទាំងអស់គ្នា '' អ្នកគ្រូ និយាយនែនាំ ទៅកាន់មិត្តរួមថ្នាក់ទាំងអស់។<br /> រីណា ស្រដីគួរសមទៅកាន់គ្រប់គ្នាទាំងទឹកមុខស្រស់ញញឹម<br /> '' សួស្តី អ្នកទាំងអស់គ្នា ''<br /> គ្រប់គ្នាក៏ឆ្លើយតបទាំងក្តីរីករាយ។</p>
<p>អ្នកគ្រូ និយាយទៅកាន់នាងជាមួយសម្តីដ៏កក់ក្តៅ<br /> '' ប្អូនអាចទៅរកកន្លែងអង្គុយណាដែលទំនេរបានតាមចិត្ត ''<br /> រីណា ឆ្លើយនឹងអ្នកគ្រូ&nbsp;<br /> '' ចាស អ្នកគ្រូ! ''<br /> ដាវីន ប្រធានថ្នាក់ដែលមានអាយុច្រើនជាងគេក្នុងថ្នាក់ បានស្រែកមកកាន់នាង&nbsp;<br /> '' អេ! មកអង្គុយតុមុខជាមួយបងមកអូន តុមុខស្រួលមើលក្តារខៀន ''&nbsp;<br /> ឧត្តម ដែលគេស្គាល់គ្រប់គ្នាថាជាបងធំប្រចាំថ្នាក់នោះ ក៏ស្រែកឃាត់&nbsp;<br /> '' ហ្អេស! មកអង្គុយខាងនេះវិញមក ជិតបង្អួចស្រួលមើលទេសភាព ស្រូបខ្យល់អាកាសផង ''<br /> បក្សពួករបស់ ឧត្តម នាំគ្នាស្រែកបន្ទរ '' មែនហើយៗ ''&nbsp;<br /> ស្របពេលដែលគ្រប់គ្នាកំពុងតែឈ្លោះប្រកែកគ្នាដើម្បីដណ្តើមនាងទៅអង្គុយជិត រីណាក្រឡេកទៅមើលតុខាងក្រោយគេបង្អស់ នាងក៏ចាប់អារម្មណ៍ឃើញ ភក្តី កំពុងអង្គុយកណ្តោចកណ្តែងតែឯង បែរមុខចេញទៅតាមមាត់បង្អួចហាក់ដូចមិនខ្វល់នឹងវត្តមានរបស់នាងចូលមកក្នុងថ្នាក់នេះដូចអ្នកឯទៀតសោះ។</p>
<p>អ្នកគ្រូនិយាយឃាត់អ្នកគ្រប់គ្នា&nbsp;<br /> '' បានហើយប្អូនៗ ឈប់ឈ្លោះប្រកែកគ្នា! អោយ រីណា សម្រេចចិត្តជ្រើសកន្លែងអង្គុយដោយខ្លួនឯងទៅ ''<br /> មិត្តរួមថ្នាក់ទាំងអស់ក៏នាំគ្នារក្សាភាពស្ងាត់ស្ងៀម។ រីណា លើកដៃចង្អុលទៅកាន់កន្លែងទំនេរក្បែរ ភក្តី រួចនាងបែរមុខនិយាយទៅកាន់អ្នកគ្រូ&nbsp;<br /> '' ខ្ញុំគិតថាកន្លែងមួយនោះសាកសមណាស់ ខ្ញុំសម្រេចចិត្តថានឹងទៅអង្គុយនៅទីនោះ ''&nbsp;<br /> ភក្តី ក៏ក្រោកមុខឡើងសម្លឹងមើលមកកាន់នាង។</p>
<p>ការសម្រេចចិត្តរបស់ រីណា ដូចជាធ្វើអោយអ្នកជាច្រើនទើសទាល់មិនពេញចិត្តសោះ តែបើអ្នកគ្រូញញឹមងក់ក្បាលហើយ ក៏គ្មាននរណាហ៊ានតវ៉ាដែរ តែ មុន្នីបុត្រ សិស្សពូកែប្រចាំថ្នាក់ ក៏ក្រោកឈរឡើងនិយាយកាត់<br /> '' អង្គុយតុក្រោយបែបនេះ ខ្ញុំបារម្ភខ្លាចតែ រីណា ពិបាកមើលក្តារខៀន ក្នុងពេលអ្នកគ្រូពន្យល់មេរៀនទេ ''<br /> រីណា ញញឹមតប<br /> '' អរគុណដែលបារម្ភ តែមិនអីទេភ្នែកខ្ញុំច្បាស់ណាស់ ''<br /> រីណា ដើរកាត់កែវភ្នែកដែលច្រណែន និង ខកចិត្ត ពីមិត្តរួមថ្នាក់ជាច្រើនទៅអង្គុយក្បែរ ភក្តី។</p>
<p><strong>&nbsp;</strong></p>
    </body>
</html>