<!DOCTYPE html>
<html>
    <body>
<p style="text-align: center; font-size: 25px;"><strong ></strong ><a href="https://www.facebook.com/hashtag/%E1%9E%9F%E1%9E%BB%E1%9E%81%E1%9F%97%E1%9E%80%E1%9F%8F%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9F%8B%E1%9E%91%E1%9F%85?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>សុខៗក៏បាត់ទៅ</strong></a><a href="https://www.facebook.com/hashtag/%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9E%98%E1%9E%A0%E1%9E%B6%E1%9E%9F%E1%9E%98%E1%9E%BB%E1%9E%91%E1%9F%92%E1%9E%9A?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>បាត់មហាសមុទ្រ</strong></a></p>
<p style="text-align: center;"><strong>និពន្ធដោយ</strong><strong>: </strong><a href="https://www.facebook.com/hashtag/%E1%9E%98%E1%9E%99%E1%9E%BC%E1%9E%9A%E1%9F%89%E1%9E%B6_%E1%9E%9B%E1%9E%B6%E1%9E%80%E1%9F%8B%E1%9E%98%E1%9E%BB%E1%9E%81?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">មយូរ៉ាលាក់មុខ</a>&nbsp;<a href="https://www.facebook.com/hashtag/%E1%9E%A0%E1%9F%81%E1%9E%84_%E1%9E%82%E1%9E%B8%E1%9E%98%E1%9E%A1%E1%9E%B6%E1%9E%84?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">ហេង គីមឡាង</a>&nbsp;</p>

<p><strong>&nbsp;&nbsp;</strong>ភក្តី អង្គុយស្ងៀមដូចគល់ឈើ សឹងតែមិនដកដង្ហើមពេលត្រូវពិសក្លិនក្រអូបសាយពីនារីម្នាក់ឯស្តាំដៃ។ រីណា កាន់កូនកន្សែងដៃពណ៍ផ្កាឈូកចេញពីក្នុងកាបូប មកជូតទឹកដែលហូរធ្លាក់ចេញពីសក់កាត់លើផ្ទៃមុខរបស់ ភក្តី ធ្វើអោយ ភក្តី អៀន រកធ្វើខ្លួនមិនត្រូវ។<br /> '' មិនមានឆ័ត្រទេរឺ ទើបបណ្តាលអោយភ្លៀងទទឹកសើមជោកបែបនេះ? '' រីណា សួរ<br /> ភក្តីតបឆ្លើយទាំងរអាករអ៊ួល<br /> '' មិ... មិនមានទេ គឺ... ដៃជាប់កាន់ចង្កូតកង់ អត់ដៃកាន់ឆ័ត្រនោះទេ ''<br /> រីណា បន្តនិយាយ<br /> '' អើយ យ៉ាងណាក៏គួរតែមានអាវភ្លៀងដែរណា ''<br /> ភក្តី ឱនមុខចុះមិនហ៊ានសម្លឹងមុខនាងចំ។<br /> រីណាក៏បន្តសួរ<br /> '' ឯងពុំមានមិត្តទេរឺ? ''<br /> ភក្តី ក្រឡេកទៅមើលមិត្តរួមថ្នាក់ទាំងអស់<br /> '' មាន គឺមានតើ ''<br /> រីណា សួរបញ្ចាក់<br /> '' គឺមិត្តស្និតស្នាលណា! ''<br /> ភក្តីគ្រវីក្បាល<br /> '' មិនមានទេ ''<br /> រីណា ញញឹម<br /> '' ខ្ញុំមកថ្មីក៏មិនមានមិត្តដែរ ក៏ល្អ! អេ យើងធ្វើជាមិត្តល្អនឹងគ្នាបានទេ? ''</p>
<p>លឺពាក្យបបួលធ្វើជាមិត្តស្និតស្នាល ភក្តី ភ្ញាក់ផ្អើលយ៉ាងខ្លាំង គិតថាវាមិនសាកសម រឺ រំភើបខ្លាំងពេក។ ដូចជាមិនគួរអោយជឿសោះ ព្រោះកន្លងមក ក្រៅពីទទួលបានការរើសអើយពីអ្នកគ្រប់គ្នាជុំវិញខ្លួននោះ ពុំដែលមាននរណាម្នាក់មកសុំគេធ្វើជាមិត្តឡើយ។</p>
<p>រីណា កេះដៃភក្តី<br /> '' អេនែ! ឆ្លើយមក! ''<br /> ភក្តីងើបមុខឡើង សម្លឹងមុខ រីណា ចំ រួចតបទាំងញញឹមតិចៗលក្ខណៈ អៀននឹងនាង<br /> '' បាទ បាន ''</p>

<p>តាមដងផ្លូវ ១៤ មិថុនា, នាពេលរសៀល ថ្ងៃរៀបលិច<br /> ភក្តី បណ្តើរកង់ដើរជាមួយ រីណា សម្លឹងទៅកាន់ផ្ទៃទឹកសមុទ្រដែលកំពុងបំពេញតួនាទីជាកញ្ចក់ឆ្លុះស្រមោលពន្លឺនៃដួងព្រះសុរិយា រៀបអស់ស្តង់គត់ទៅ នៅតែទឹករលកសមុទ្រ ធ្វើចលនាតាមចង្វាក់តន្រ្តី បក្សីបក្សា ច្រៀងលេងជាភ្លេង បំពេរវាយោសមុទ្របក់មកបបួលរុក្ខជាតិផ្កា ដែលកំពុងអមសងខាងផ្លូវអោយរេរាំជាមួយ បង្កើតបានជាបរិយាកាសដ៏ល្អលំហែរ លួងលោមមើលថែ ដួងចិត្តមនុស្សលោក អោយបានសំរាកពីការងារនឹងវិលត្រលប់ទៅលំនៅស្ថានវិញយ៉ាងរីករាយ។</p>
<p>'' ឪពុកម្តាយ របស់ឯងប្រករបរនេសាទនៅតាមឆ្នេរសមុទ្រនេះមែនទេ? '' រីណា សួរទៅកាន់ ភក្តី<br /> ភក្តី តប<br /> '' ហ៊ឺម! ត្រូវហើយ ពួកគាត់បានឡើងសំពៅចេញនេសាទបាត់ ៥សប្តាហ៍ហើយ ពុំទាន់ឃើញវិលត្រលប់មកវិញទេ ''<br /> រីណា បន្តសួរ<br /> '' បែបនេះ ឯងប្រហែលជានៅផ្ទះតែឯងហើយ? ''<br /> ភក្តី ងក់ក្បាល។ រីណា សួរទៀត<br /> '' ឯងមានអារម្មណ៍ថាឯកាទេ? ''<br /> ភក្តី ឆ្លើយ<br /> '' ធ្លាប់ទៅហើយ ព្រោះតាំងពីក្មេងមក ពួកគាត់ទុកខ្ញុំនៅផ្ទះតែឯង ព្រោះពួកគាត់រវល់នឹងការចេញនេសាទ ''<br /> រីណា ដកដង្ហើមធំ<br /> '' ហ៊ឺម! ឯងមិនខុសពី ខ្ញុំ ទេបើចឹង ''<br /> ភក្តីងាកទៅមើលមុខ រីណា<br /> '' ចុះ រីណា ឯងវិញ យ៉ាងម៉េចទៅ? ''</p>
<p>ព្រះអាទិត្យក៏លិចលង់បំបាំងកាយពួនចូលទៅផុតផ្ទៃទឹកសមុទ្រដ៏វែងអន្លាយ<br /> ផុតកន្ទុយភ្នែក រលត់បាត់ពន្លឺងងឹតស្លប់ ជំនួសដោយវង់ព្រះចន្ទមកលំអរកាយនាពេលរាត្រី។ អំពូលភ្លើងតាមដងវិថីក៏ចាប់ផ្តើមបើកបញ្ចាំងមក បម្រើតម្រូវការដល់អ្នកធ្វើដំណើរតាមផ្លូវ។</p>
<p>រីណា និយាយ<br /> '' មានរឿងខ្លះ ខ្ញុំប្រាប់ឯងត្រង់ ប្រហែលជាគិតថាឯងមិនជឿ ខ្ញុំ ទេ! តែខ្ញុំនឹងព្យាយាមពន្យល់ឯង! ឯងដែលស្តាប់ព្រេងនិទានលើលោកនេះទេ? គឺព្រេងនិទានដែលគ្រប់គ្នាធ្លាប់ជឿថាវាមិនមានពិតអាចកើតឡើងនោះទេ! វាមានតែក្នុងរឿងព្រេងនិទានតែប៉ុណ្ណោះ ដូចជារឿងនិទាននិយាយអំពី វេទមន្ត រឿងអច្ឆរិយៈ រឿងអបីយជំនឿផ្សេងៗ! ឯងដែលលឺព្រេងនិទាន និយាយអំពី វិមាន ដ៏ធំស្កឹមស្កៃមួយទេ? ''<br /> ភក្តី ឆ្លើយ<br /> '' ធ្លាប់! កាលពីតូច ម៉ាក់ខ្ញុំធ្លាប់និទានរឿង វិមានស្តេចមច្ឆាក្រោមបាតសមុទ្រអោយស្តាប់ ''<br /> រីណា ប្រែទឹកមុខ រួចសម្លឹងមុខ ភក្តី ក្នុងន័យចង់ប្រាប់អ្វីម៉្យាងដល់រូបគេ តែនាងគិតថា ពុំទាន់ដល់ពេលដែលគួរប្រាប់នោះឡើយ។</p>
<p>ភក្តី សួរ<br /> '' ចុះផ្ទះរបស់ រីណា ឯងនៅទីណាដែរ? ''<br /> រីណា តប<br /> '' សូមទោស! ខ្ញុំមិនទាន់ចង់ប្រាប់ឯងអោយដឹងនៅពេលនេះទេ មានឱកាស ខ្ញុំនឹងប្រាប់ឯងអោយដឹង តែពេលនេះខ្ញុំស្នាក់នៅផ្ទះជួលតែម្នាក់ឯងទេ ''<br /> ភក្តី បន្តសួរ<br /> '' ខ្ញុំជូនទៅផ្ទះទេ? ''<br /> រីណា ប្រកែក<br /> '' ទេ! យប់ហើយ ក្រែងឯងត្រូវប្រញាប់ទៅផ្ទះឯងដែរ ខ្ញុំអាចចាំឡានក្រុងបានណា! ''<br /> ភក្តីញញឹមស្រស់ ជាលើកដំបូងដែលបង្ហាញអោយរីណាបានឃើញ ពីទឹកមុខរីករាយលើផ្ទៃមុខរបស់នាយ<br /> '' មិនអីទេ! ឡើងកង់មក ខ្ញុំនឹងជូន រីណា ឯងទៅផ្ទះ ''<br /> រីណា អស់ពាក្យនឹងប្រកែក ក៏ព្រមឡើងអង្គុយលើកង់ពីក្រោយខ្នងភក្តី អោយនាយធាក់កង់ជូននាងទៅផ្ទះវិញ ក្រោមពន្លឺនៃដួងតារាជាច្រើនព្រះអង្គជាបរិវារនៃដួងខែ។</p>
<p><strong>&nbsp;</strong></p>
    </body>
</html>