<!DOCTYPE html>
<html>
    <body>
<p style="text-align: center; font-size: 25px;"><strong ></strong ><a href="https://www.facebook.com/hashtag/%E1%9E%9F%E1%9E%BB%E1%9E%81%E1%9F%97%E1%9E%80%E1%9F%8F%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9F%8B%E1%9E%91%E1%9F%85?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>សុខៗក៏បាត់ទៅ</strong></a><a href="https://www.facebook.com/hashtag/%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9E%98%E1%9E%A0%E1%9E%B6%E1%9E%9F%E1%9E%98%E1%9E%BB%E1%9E%91%E1%9F%92%E1%9E%9A?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>បាត់មហាសមុទ្រ</strong></a></p>
<p style="text-align: center;"><strong>និពន្ធដោយ</strong><strong>: </strong><a href="https://www.facebook.com/hashtag/%E1%9E%98%E1%9E%99%E1%9E%BC%E1%9E%9A%E1%9F%89%E1%9E%B6_%E1%9E%9B%E1%9E%B6%E1%9E%80%E1%9F%8B%E1%9E%98%E1%9E%BB%E1%9E%81?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">មយូរ៉ាលាក់មុខ</a>&nbsp;<a href="https://www.facebook.com/hashtag/%E1%9E%A0%E1%9F%81%E1%9E%84_%E1%9E%82%E1%9E%B8%E1%9E%98%E1%9E%A1%E1%9E%B6%E1%9E%84?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">ហេង គីមឡាង</a>&nbsp;</p>

<p><strong>&nbsp;&nbsp;</strong>អស់ពេលមួយរយៈធំមក ទំនាក់ទំនងមិត្តស្និតស្នាលប្រុសស្រីវិទ្យាល័យមួយគូរនេះ ក៏បង្កើតបានជាព្រួញកាមទេពបាញ់ទម្លុះបេះដូងកំលោះវ័យក្មេង អោយកើតមានចិត្តលង់លួចស្រលាញ់ខាងស្រីដោយមិនដឹងខ្លួន។</p>
<p>ផ្កាម្លិះ ព្រាត់មែករសាត់តាមព្រះពាយ មកទើលើមាត់បង្អួចក្បែរកន្លែងដែល ភក្តី អង្គុយ នាយក៏យកដៃចាប់កាន់វាមកមើល គ្រានោះ ដៃនៃនារីជាមិត្តស្និតស្នាលក៏ឈោងមកយកផ្កាម្លិះមួយទង ចេញពីដៃនាយទៅស៊កនៅលើត្រចៀករបស់នាង រួចនាងក៏សួរទាំងដិតជាប់ស្នាមញញឹម ទៅកាន់ ភក្តី ថា<br /> '' យ៉ាងម៉េចដែរ? ''<br /> ភក្តី ក៏អស់សំណើច<br /> '' រីណា ឯងចេះកំប្លែងទៀត ''<br /> រីណា ទម្លាក់ទឹកមុខចុះរួចសម្លត់ ភក្តី<br /> '' កំប្លែងត្រង់ណា? ''<br /> ភក្តី បញ្ឈប់ការសើច នៅពេលដែលឃើញវត្តមាន ណារ៉ុន ដើរសំដៅមករក រីណា។<br /> '' រីណា! នាងអាចចេញក្រៅជាមួយខ្ញុំបន្តិចបានទេ ខ្ញុំមានរឿងសំខាន់ចង់និយាយជាមួយនាង ''</p>
<p>ណារ៉ុន និយាយ<br /> រីណា ក្រោកឈរឡើង ងក់ក្បាលទទួលការយល់ព្រមជាមួយនឹងគេដើរចេញទៅខាងក្រៅ។ ភក្តី ចាប់ផ្តើមមានអារម្មណ៍ទើសទាល់ក្នុងចិត្ត រកស្មានថាមិនត្រូវជាអារម្មណ៍បែបណា។</p>
<p>ណារ៉ុន ជាកូនថៅកែភោជនីយដ្ឋានមួយដ៏ធំ ដែលនរណាក៏ល្បីពីយូរណាស់មកហើយថា រូបគេ ជាកំពូលបុរសដើរញ៉ែស្រីពេញតែសាលា។គ្រាន់តែទៅដល់ខាងមុខសាលាភ្លាម ណារ៉ុន ក៏ដកកុលាបមួយទងជូន</p>
<p>&nbsp;រីណា ធ្វើអោយនាងភ្ញាក់ផ្អើលជាខ្លាំង<br /> '' នេះគឺជាអ្វី? ''<br /> ណារ៉ុន និយាយចេញមកជាមួយទឹកមុខដ៏ស្រទន់ ទាក់ទាញមន្តស្នេហ៍<br /> '' ទទួលយកក្តីស្រលាញ់ពីខ្ញុំទៅណា ''<br /> គ្រាន់តែ រីណា ទទួលយកផ្កាកុលាបពីដៃរបស់ ណារ៉ុន ភ្លាមនោះ ភក្តី ក៏ស្ទុះទាំងកំហឹងទៅដណ្តើមយកវាពីដៃនាង ចោលទៅលើដី<br /> '' កុំទទួលយករបស់នេះពីវាអី វាជាមនុស្សមិនល្អទេ ''<br /> រីណា បើកភ្នែកធំៗមើលមុខ ភក្តី ព្រោះវាជាលើកទីមួយហើយ ដែលរូបនាងបានឃើញ នាយ បញ្ចេញកំហឹងបែបនេះ។ ដូចដែលគេធ្លាប់និយាយចឹង ស្នេហា គឺប្រៀបដូចជាភ្លើងដ៏ក្តៅ មានកំដៅក្តៅជាងអណ្តាតភ្លើងនៃព្រះអាទិត្យទៀត ចេះស្រលាញ់កាន់តែខ្លាំង ក៏កើតអោយមានចិត្តប្រច័ណ្ឌដែលអាចធ្វើអោយមនុស្សធ្លាប់តែស្លូតសុភាពរាបសារ ប្រែក្លាយជាកាចសាហាវតែមួយរំពេច។</p>
<p>ណារ៉ុន ខឹងយ៉ាងខ្លាំង ដើរទៅច្រាន ភក្តី ខ្ទប់ជញ្ចាំង ធ្វើអោយ ភក្តី ទប់នឹងការខឹងលែងបាន ដាល់ ណារ៉ុន មួយដៃកណ្តាលមុខ ដាច់ផ្ងារក្រោយដួលទៅនឹងដី។<br /> រីណា ស្រែកឃាត់ ភក្តី<br /> '' ភក្តី! ឯងមិនគួរវៃគេបែបនេះទេ! ''</p>
<p>មិត្ត របស់ ណារ៉ុន គឺ ឧត្តម ដែលគេឯងស្គាល់ហើយថាជា បងធំប្រចាំថ្នាក់នោះ បានបបួលគ្នីគ្នាស្ទុះចូលមកព្រួតវាយ ភក្តី ពេញទំហឹងយ៉ាងចាស់ដៃ។ រីណា បានខំប្រឹងឃាត់គេឯងគ្រប់គ្នាដែរ តែឃាត់មិនឈ្នះកម្លាំងបាយរបស់ប្រុសៗឡើយ បានត្រឹមតែបណ្តោយអោយ ភក្តី ទុ្រឌទ្រោមទៅតាមការចាត់ការមួយអស់ខ្យល់ពីក្រុមរបស់ ឧត្តម។ រហូតដល់ ភក្តី ដេកក្រាបនឹងដី ទើបគ្រប់គ្នាដងដៃ ដកជើងដើរចេញ បន្ធូរអោយ នាយបានដកដង្ហើម។ រីណា ទ្រហោយំ ស្ទុះទៅឱប ភក្តី ដែលពោរពេញដោយរបួសទារុណកម្មពេញខ្លួន សឹងតែសន្លប់បាត់បង់ស្មារតី ព្រោះតែអាណិតនាយពេក។</p>

<p><strong>&nbsp;</strong></p>
    </body>
</html>