<!DOCTYPE html>
<html>
    <body>
<p style="text-align: center; font-size: 25px;"><strong ></strong ><a href="https://www.facebook.com/hashtag/%E1%9E%9F%E1%9E%BB%E1%9E%81%E1%9F%97%E1%9E%80%E1%9F%8F%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9F%8B%E1%9E%91%E1%9F%85?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>សុខៗក៏បាត់ទៅ</strong></a><a href="https://www.facebook.com/hashtag/%E1%9E%94%E1%9E%B6%E1%9E%8F%E1%9E%98%E1%9E%A0%E1%9E%B6%E1%9E%9F%E1%9E%98%E1%9E%BB%E1%9E%91%E1%9F%92%E1%9E%9A?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R"><strong>បាត់មហាសមុទ្រ</strong></a></p>
<p style="text-align: center;"><strong>និពន្ធដោយ</strong><strong>: </strong><a href="https://www.facebook.com/hashtag/%E1%9E%98%E1%9E%99%E1%9E%BC%E1%9E%9A%E1%9F%89%E1%9E%B6_%E1%9E%9B%E1%9E%B6%E1%9E%80%E1%9F%8B%E1%9E%98%E1%9E%BB%E1%9E%81?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">មយូរ៉ាលាក់មុខ</a>&nbsp;<a href="https://www.facebook.com/hashtag/%E1%9E%A0%E1%9F%81%E1%9E%84_%E1%9E%82%E1%9E%B8%E1%9E%98%E1%9E%A1%E1%9E%B6%E1%9E%84?source=feed_text&amp;epa=HASHTAG&amp;__xts__%5B0%5D=68.ARDrkwaqsz0viTxFW6VsAdGix8gIAWQXgpx8pGS1tEdryjNwZr3It0TIeEVwy7VJdAtjDJxaTBQ1Mf4lZQbXSB3iLhVuGMFpJoVGIqZxBB2HfxJGVstDr3Y8XgfQBycJbS6opjdleoPJZ2axcX4fWDlU1JqR_Q1KmZZ0Ul_t-8y3ondy8YiFzCV3mDPqJxw8a_9LFMVWyCuFP-f43unB7a_2hKohnAuxi-72OV9aBc8jspn74_jQPUVAk9vuqSGUKeNmR3zARJOBWTcDT61mCrd08I4VRB7PyVnCfpONeVxMNbbZkhrnrsXzuFYOlG9O3U_fD81WxBa4ubExvf62-D0&amp;__tn__=%2ANK-R">ហេង គីមឡាង</a>&nbsp;</p>

<p><strong>&nbsp;&nbsp;</strong>សៀលវេលាដដែលប្រហែលនឹងថ្ងៃពួកគេទាំងពីរធ្លាប់ណាត់គ្នាមកដើរលេងថ្ងៃដំបូង...<br /> ផ្ទៃទឹកសមុទ្រនៅមានស្រមោលពន្លឺព្រះអាទិត្យក្រហមព្រៀកៗនៅឡើយ រីណា កំពុងលាបថ្នាំរបួសអោយ ភក្តី អង្គុយលើថ្មដ៏ធំមួយឯឆ្នេរសមុទ្រ មានកង់កញ្ចាស់មួយផ្អែកពីក្រោយ។<br /> រីណា ចាប់ផ្តើមពាក្យសន្ទនាដំបូងសួរទៅកាន់ ភក្តី&nbsp;<br /> '' ឯងប្រច័ណ្ឌមែនទេ ពេលឃើញគេមកសុំស្រលាញ់ ខ្ញុំ បែបនេះ? ''<br /> ភក្តី ទាល់សំដីនិយាយអ្វីមិនចេញ តែរីណាក៏សួរម្តងទៀត<br /> '' ឆាប់ឆ្លើយនឹងសំនួររបស់ខ្ញុំមក ''<br /> ភក្តី បន្ធូរដង្ហើមហើយ និយាយ&nbsp;<br /> '' ខ្ញុំមិនដឹងទេ ''<br /> រីណា នៅស្ងៀម ហាក់មានបំណងរងចាំស្តាប់ ភក្តី និយាយបន្ត។<br /> '' មែនហើយ គឺប្រច័ណ្ឌ '' ភក្តី បន្តនិយាយ&nbsp;<br /> រីណា ក្រឡេកទៅមើលមុខ ភក្តី ជាមួយកែវភ្នែកថ្លាឆ្វង់&nbsp;<br /> '' ហេតុអ្វីទើប មិត្ត ចេះប្រច័ណ្ឌ? ''<br /> ភក្តី ឳនមុខចុះ រៀបនឹងហារមាត់និយាយ ស្រាប់តែមានព្យុះភ្លៀងដ៏កាចសាហាវបក់បោកមក ពីផ្ទៃសមុទ្រយ៉ាងសាហាវ ជាមួយនឹងសម្លេងផ្គររន្ទះលាន់សន្ធឹក។</p>
<p>ទេវរាជ ស្តេចមហាសមុទ្រ ដឹកនាំកងពលសេនាមច្ឆា ក្រោកឡើងពីបាតសមុទ្រមកឡោមព័ទ្ធពួកគេទាំង២ ធ្វើអោយ ភក្តី ភ័យខ្លាចយ៉ាងខ្លាំង។ ដោយអំណាចនៃពូជពង្សាវតា មច្ឆា សាយភាយឡើងមកលើគោក បណ្តាលអោយជើងទាំងគូររបស់ រីណា ប្រែក្លាយទៅជាកន្ទុយត្រីមច្ឆា។ ការពិត ភក្តី ទើបតែដឹងថា រីណា គឺជាទេពមច្ឆា។ រីណា បានត្រឹមតែញញឹមលា ភក្តី ទាំងទឹកភ្នែករសាត់ជាដំណក់ៗ តាមខ្យល់នៃមហិទ្ធិរិទ្ធរបស់ ស្តេចមច្ឆា ជាបិតានៃ ព្រះនាង ទេពមច្ឆាណារី (ឈ្មោះពិតរបស់ រីណា) គួចយកនាងចេញពីភក្តី។ ភក្តីប្រឹងរត់ដេញតាមនាង ក៏ត្រូវសេនាឯកនៃទ័ពមច្ឆាវាយមួយដំបងដួលទៅលើដីខ្សាច់សមុទ្រ។ ព្រះបុត្រីនៃស្តេចមច្ឆា ទម្លាក់ដបកែវថ្មមួយដែលមានសំបុត្រខាងក្នុងនោះទៅអោយភក្តីរួចនិយាយាពាក្យចុងក្រោយ&nbsp;<br /> '' នេះគឺជាបណ្តាំរបស់ ឪពុកម្តាយ ឯងដែលបានពឹង ខ្ញុំ យកវាមកអោយឯង ''</p>
<p>មួយរំពេចនោះ អ្នកទាំងអស់ក៏រលាយខ្លួនបាត់ទៅ បន្សល់នូវភាពស្ងប់ស្ងាត់កណ្តោចកណ្តែង អោយ ភក្តី នៅតែម្នាក់ឯង ក្នុងរាត្រីដ៏ឯកា។ ភក្តី បានត្រឹមតែយំសោក ស្រែកប្រាប់ ផ្ទៃសមុទ្រដ៏ធំល្វឹងនោះថា&nbsp;<br /> '' ចម្លើយដែល ខ្ញុំ ចង់ឆ្លើយប្រាប់ នាងមុនហ្នឹងបន្តិចគឺចង់ប្រាប់នាងថា... ខ្ញុំ ស្រលាញ់នាង រីណា ''</p>
<p>ខ្យល់បក់ '' វូ '' កាត់តាមឆ្នេរសមុទ្រ ត្រជាក់ស្រៀវស្រឹប ភក្តី ដើរទៅរើសយកដបកែវថ្ម មួយនោះមកបើកគម្របទាញយកសំបុត្រខាងក្នុងនោះយកមកអាន។<br /> ទើបតែដឹងការពិត ប៉ុន្មានសប្តាហ៍មុន បន្ទាប់ពីក្រុមអ្នកនេសាទ ចេញសំពៅទៅនេសាទលើមហាសមុទ្របានមួយសប្តាហ៍ ក៏បានឆ្លងកាត់ពីលើទឹកដីរបស់ ស្តេចមច្ឆា ដោយគ្មានការបន់ស្រន់ សុំការអនុញ្ញាតត្រឹមត្រូវ បណ្តាលអោយស្តេចមច្ឆាផ្ទុះកំហឹងដោយការប្រកាន់ លើកទ័ពមកបង្ករព្យុះភ្លៀង រលកយក្សបោកសម្លាប់មនុស្សក្នុងសំពៅទាំងនោះ ស្លាប់ទាំងអស់។ ប៉ុន្មានថ្ងៃក្រោយ វិញ្ញាណ លោក ហាន់ និង មីង សួន ដែលជា ឪពុកម្តាយ របស់ ភក្តី បានទៅពឹងពាក់ បុត្រីស្តេច មច្ឆា គឺព្រះនាង មច្ឆាណារី ជួយយកដំណឹងនោះ មកប្រាប់កូនប្រុសរបស់ពួកគាត់។</p>
<p>តើ ភក្តី នឹងស្អប់ រីណា ទេពេលដឹងថា ឪពុករបស់នាង ជាអ្នកសម្លាប់ ឪពុកម្តាយ របស់រូបគេ?</p>
<p><strong>&nbsp;</strong></p>
    </body>
</html>